version: '2'
services:
  super_zoo_1:
    image: zookeeper
    restart: always
    container_name: super_zoo_1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=super_zoo_1:2888:3888;2181 server.2=super_zoo_2:2888:3888;2181 server.3=super_zoo_3:2888:3888;2181

  super_zoo_2:
    image: zookeeper
    restart: always
    container_name: super_zoo_2
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=super_zoo_1:2888:3888;2181 server.2=super_zoo_2:2888:3888;2181 server.3=super_zoo_3:2888:3888;2181

  super_zoo_3:
    image: zookeeper
    restart: always
    container_name: super_zoo_3
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=super_zoo_1:2888:3888;2181 server.2=super_zoo_2:2888:3888;2181 server.3=super_zoo_3:2888:3888;2181
